version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install R and TeX
          command: apt-get update && apt-get install -y r-recommended texlive-latex-base texlive-fonts-recommended
      - run:
          name: Install dependencies
          command: echo 'options(repos = structure(c(CRAN = "https://cloud.r-project.org/"))) ; install.packages(c("coda", "ggplot2", "mcmc", "SamplerCompare"))' | R --vanilla
      - run:
          name: R CMD check
          command: R CMD build . && R CMD check ACTCompare_*.tar.gz
